Inventory/urls.py
from django.urls import path

from . import views
app_name = "inventory"
urlpatterns = [
    path("", views.index, name="index")
]

SMSolution/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("user/",include("User.urls")),
    path("admin/", admin.site.urls),
    path("inventory/",include("Inventory.urls")),


]

User/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.signup_view, name="register")

]

Inventory/models.py
from django.db import models

# Create your models here.

User/models.py
from django.db import models

# Create your models here.

Customer/views.py
from django.shortcuts import render

# Create your views here.

Inventory/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect , HttpResponse
# Create your views here.


def index(request):
    return HttpResponse("Inventory Management")

PointOfSale/views.py
from django.shortcuts import render

# Create your views here.

User/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.shortcuts import render , redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
# Create your views here.


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("user:login"))
    return render(request, "user/login.html")


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("inventory:index"))
        else:
            return render(request, "user/login.html", {
                "message": "Invalid Credentials"
            })
    return render(request, "user/login.html")


def logout_view(request):
    logout(request)
    return render(request, "user/login.html",{
        "message": "Logged Out."
    })


def signup_view(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            messages.success(request, "Registration successful.")
            return HttpResponseRedirect(reverse("user:login"))
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="user/register.html",
                  context={"register_form":form})

User/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    {% if message %}
    <label>{{message}}</label>
    {% endif %}
    <form action="{% url 'user:login' %}" method="POST">
        {% csrf_token %}
        <div>
        <input type="text" name="username" placeholder="UserName">
        </div>
        <div>
            <input type="password" name="password" placeholder="Password">
        </div>
        <a href="{% url 'user:register' %}">don't have an Account?signUp</a>
        <div>
            <input type="submit" value="Sign-in">
        </div>
    </form>
</body>
</html>

User/templates/user/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form}}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	If you already have an account, <a href="{% url 'user:index' %}">login</a> instead.
</div>
</body>
</html>